# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
# package
# node
# folder
# frame
# cloud
# database
# interface
@startuml

header ArchivesSpace


cloud "ArchivesSpace" {
  component "Front-End"
  component "Public"
  component "Backend" {
    database "RDBMS"
  }
}

package "rarebooks.library.nd.edu"

interface "further description" as FurtherDescription

folder "LoadingDock"
node "Oxygen"
node "BitCurator" {
  component "Checksums"
  component "Digital\nForensics"
}

ArchivesSpace .(0).> rarebooks.library.nd.edu : "For links\nto further description"
ArchivesSpace .(0).> collections.library.nd.edu : "For links\nto further description"
ArchivesSpace .(0).> curate.nd.edu : "For links\nto further description"
ArchivesSpace ..( FurtherDescription
@enduml
