# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
# package
# node
# folder
# frame
# cloud
# database
# interface
@startuml

header CDS

collections "Digital Signage" as DS
collections "Equipment Images" as EI
collections "Space Images" as SI
collections "CDS Workshops" as CDSW
collections "Love Data Week Presentations" as LDWP
collections "Library Research Award" as LRA
collections "CDS Knowledge Base" as CDSKB
collections "Digital Humanities Workshop" as DHW
collections CSVs

cloud ArchivesSpace
cloud Box
cloud Github
cloud GoogleDrive
cloud GoogleSites
cloud GoogleSuite
cloud JSTor
cloud LibCal
cloud Mendalay
cloud OSF
cloud QUaltrics
cloud ReclaimHosting
cloud Refworks
cloud Tableau
cloud Zotero
folder LoadingDock
node "Notepad++" as NP
node Excel
node OxygenXML
node PDFAnnotator
node SocialScienceSoftware
node TopicModelingSoftare
node VSCode
node Photoshop
node Illustrator
package CurateND
package DEC
package FilemakerPro
package LibGuids

JSTor .(0).> CSVs
TopicModelingSoftare .(0).> CSVs
SocialScienceSoftware .(0).> CSVs
FilemakerPro .(0).> LoadingDock
CSVs .(0).> DEC
DEC .(0).> GoogleDrive : "For image\nURL reference"
DEC .(0).> GoogleDrive : "For bulk\nimage editing"
ArchivesSpace .(0).> GoogleDrive : "For work to\nimport FilemakerPro"

DS ..> Box
CDSW ..> Github
LRA ..> CurateND
LDWP ..> OSF
CDSKB ..> GoogleSites
CDSKB ..> GoogleSuite
EI ..> LibCal
SI ..> LibCal
DHW ..> LibGuids

@enduml
