# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
# package
# node
# folder
# frame
# cloud
# database
# interface
@startuml

header CDS

collections "Digital Signage" as DS
collections "Equipment Images" as EI
collections "Space Images" as SI
collections "CDS Workshops" as CDSW
collections "Love Data Week Presentations" as LDWP
collections "Library Research Award" as LRA
collections "CDS Knowledge Base" as CDSKB
collections "Digital Humanities Workshop" as DHW
collections "CSVs"

cloud Box
cloud Github
cloud GoogleSites
cloud GoogleSuite
cloud LibCal
cloud Mendalay
cloud OSF
cloud QUaltrics
cloud ReclaimHosting
cloud Refworks
cloud Tableau
cloud Zotero
node "Notepad++" as NP
node OxygenXML
node PDFAnnotator
node VSCode
node Excel
package CurateND
package FilemakerProp
package LibGuids
node SocialScienceSoftware
node TopicModelingSoftare
cloud JSTor

JSTor .(0).> CSVs
TopicModelingSoftare .(0).> CSVs
SocialScienceSoftware .(0).> CSVs

DS ..> Box
CDSW ..> Github
LRA ..> CurateND
LDWP ..> OSF
CDSKB ..> GoogleSites
CDSKB ..> GoogleSuite
EI ..> LibCal
SI ..> LibCal
DHW ..> LibGuids

@enduml
