# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
# package
# node
# folder
# frame
# cloud
# database
# interface
@startuml

header CurateND

package "curate.nd.edu" {
  component "Object Model" as CurateOM
  component "Workers" as CurateW
  component "Business Logic" as CurateBL
  database MySQL
  interface "API" as CurateAPI
  CurateW --> CurateOM
  CurateBL --> MySQL
}
package Disadis {
  folder "Web Logs" as WebLogs
}

cloud OSF
CurateBL --> OSF
cloud Orcid
CurateBL --> Orcid

package DEC
package NDPress
package Locabulary
package PresQT

PresQT --> CurateAPI

CurateOM ..> Disadis
CurateBL ..> DEC : Link to exhibits
CurateBL ..> NDPress : Link for books
CurateOM ..> Locabulary : "for\ncontrolled\nvocabulary"

package "Fedora" {
  interface "HTTP Interface" as FedoraHTTP
  folder "File System" as FedoraFS
}
note bottom of Fedora
  For durable storage
end note

package "Solr" {
  interface "HTTP Interface" as SolrHTTP
}
note bottom of Solr
  For search
end note

package "Batch" {
  interface API as BatchAPI
  component "System\nWorkers" as BatchWorkers
  component Staging as BatchStaging
  BatchWorkers --> BatchStaging
}

package "Bendo" {
  interface API as BendoAPI
  component Cache as BendoC
  component Storage {
    component "Copy on\nWrite Layer" as BendoCOW
    component "Preservation\nLayer" as BendoPL
  }
}

package "DTernity" {
  interface "NFS Mount" as DTernityNFSM
  interface "CIFS Mount" as DTernityCIFSM
  package "Storage" as DTernityStorage {
    component "Cloud" as DternityCS
    component "Tape" as DternityTS
  }
}

folder "Local Storage" {
  interface "NFS Mount" as LocalNFSMount
}

folder "SpectraLogic"

cloud "FujiCloud"

cloud AWS {
  component S3
}

cloud EZid {
  component DOIService as EZidDoiService
}
CurateBL --> EZidDoiService
BatchWorkers --> EZidDoiService

package Noids {
  database MySQL as MySQLNoids
}
CurateBL --> Noids
BatchWorkers --> Noids

package "curate metrics" {
  component "Harvester"
  Harvester --> WebLogs
  Harvester --> FedoraHTTP
  Harvester --> FedoraFS
  Harvester --> BendoAPI
}

BendoPL --> DTernityNFSM
CurateOM --> FedoraHTTP
CurateOM --> SolrHTTP
BatchWorkers --> CurateAPI
BendoCOW --> LocalNFSMount
DternityTS --> SpectraLogic
DternityCS --> FujiCloud
BendoC --> S3
CurateW --> BatchAPI
BatchWorkers --> BendoAPI
BatchWorkers --> FedoraHTTP
BatchWorkers --> LocalNFSMount
BatchStaging --> LocalNFSMount
Disadis --> FedoraHTTP
CurateBL --> Disadis

@enduml
