# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
# package
# node
# folder
# frame
# cloud
# database
# interface
@startuml

header DAS

actor MetadataDiscoverySystemSpecialist
cloud ArchivesSpace
cloud OCLC
cloud Primo
collections ArchitectureScans
collections BuildingSouthBend
collections DiscoveryCollection
collections MARCRecords
collections RomeApp
folder LDrive
node MARCModifier
package Aleph
package CORAL
package CurateND
package FTPPrimoJob
package LibraryWebServer
package SFX

ArchitectureScans --> LibraryWebServer
BuildingSouthBend --> LibraryWebServer
MetadataDiscoverySystemSpecialist --> MARCModifier
MetadataDiscoverySystemSpecialist --> CORAL : For correspondence\nw/ vendor
DiscoveryCollection --> Primo
FTPPrimoJob --> Aleph
FTPPrimoJob --> Primo
MARCModifier --> MARCRecords
MARCRecords --> LDrive
OCLC --> MARCRecords
Primo --> ArchivesSpace
Primo --> SFX
RomeApp --> LibraryWebServer
SFX --> CurateND


@enduml
