# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
@startuml
node HesburghLibraries
note bottom of HesburghLibraries
  Without this node,
  the diagram renders as
  a sequence diagram
end note

actor AaronB
actor AdamH
actor AlexP
actor AmandaG
actor AnnaMM
actor DanJ
actor DeborahH
actor DeniseM
actor ElizabethH
actor EricD
actor EricLM
actor ErikaH
actor IanA
actor JamesC
actor JenniferP
actor JulieV
actor LaurenA
actor MelissaH
actor MikalaN
actor PatrickM
actor PatrickR
actor RandyH
actor SandyS
actor SarahW

AlexP --> AmandaG
AlexP --> DanJ
AlexP --> ElizabethH
AlexP --> EricD
AlexP --> EricLM
AlexP --> JulieV
AlexP --> MattS
AlexP --> MikalaN
AlexP --> PatrickR
AlexP --> ScottK
AmandaG --> AdamH
AmandaG --> DanJ
AmandaG --> DeniseM
AmandaG --> EricD
AmandaG --> EricLM
AmandaG --> JessicaM
AmandaG --> MattS
AmandaG --> MikalaN
AmandaG --> MikeR
AmandaG --> NatalieM
AmandaG --> SarahW
AmandaG --> ScottK
DeniseM --> AmandaG
DeniseM --> MaryR
DeniseM --> MikalaN
DeniseM --> MikeR
DeniseM --> SarahW
ElizabethH --> AmandaG
ElizabethH --> DeniseM
ElizabethH --> EricD
ElizabethH --> PatrickR
ElizabethH --> SarahW
ElizabethH --> ScottK
JulieV --> AndyW
JulieV --> AnnaMM
JulieV --> DanJ
JulieV --> EricLM
JulieV --> MattS
JulieV --> RandyH
LaurenA --> AaronB
LaurenA --> AdamH
LaurenA --> DeniseM
LaurenA --> ErikaH
LaurenA --> IanA
LaurenA --> JenniferP
LaurenA --> JuliaS
LaurenA --> MelissaH
LaurenA --> SandyS
MikalaN --> AmandaG
MikalaN --> DanJ
MikalaN --> DeniseM
MikalaN --> EricLM
MikalaN --> LaurenA
MikalaN --> PatrickM
MikalaN --> PatrickR
MikalaN --> SarahW
PatrickM --> AmandaG
PatrickM --> DeborahH
PatrickM --> ElizabethH
PatrickM --> EricD
PatrickM --> JamesC
PatrickM --> PatrickR
PatrickM --> SarahW
PatrickR --> AdamH
PatrickR --> DanJ
PatrickR --> DeniseM
PatrickR --> EricD
PatrickR --> EricLM
PatrickR --> JessicaM
PatrickR --> MattS
PatrickR --> MikalaN
PatrickR --> MikeR
PatrickR --> NatalieM
PatrickR --> SarahW
PatrickR --> ScottK

@enduml
