# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
@startuml
node HesburghLibraries
note bottom of HesburghLibraries
  Without this node,
  the diagram renders as
  a sequence diagram
end note

actor AlexP
actor AmandaG
actor DanJ
actor DeborahH
actor DeniseM
actor ElizabethH
actor EricD
actor EricLM
actor JamesC
actor JulieV
actor LaurenA
actor MikalaN
actor PatrickM
actor PatrickR
actor SarahW

AlexP --> AmandaG
AlexP --> DanJ
AlexP --> ElizabethH
AlexP --> EricD
AlexP --> EricLM
AlexP --> JulieV
AlexP --> MattS
AlexP --> MikalaN
AlexP --> PatrickR
AlexP --> ScottK
AmandaG --> AdamH
AmandaG --> DanJ
AmandaG --> DeniseM
AmandaG --> EricD
AmandaG --> EricLM
AmandaG --> JessicaM
AmandaG --> MattS
AmandaG --> MikalaN
AmandaG --> MikeR
AmandaG --> NatalieM
AmandaG --> SarahW
AmandaG --> ScottK
MikalaN --> DanJ
MikalaN --> DeniseM
MikalaN --> EricLM
MikalaN --> LaurenA
MikalaN --> PatrickM
MikalaN --> SarahW
MikalaN <--> AmandaG
MikalaN <--> PatrickR
PatrickM --> AmandaG
PatrickM --> DeborahH
PatrickM --> ElizabethH
PatrickM --> EricD
PatrickM --> JamesC
PatrickM --> PatrickR
PatrickM --> SarahW
PatrickR --> AdamH
PatrickR --> DanJ
PatrickR --> DeniseM
PatrickR --> EricD
PatrickR --> EricLM
PatrickR --> JessicaM
PatrickR --> MattS
PatrickR --> MikalaN
PatrickR --> MikeR
PatrickR --> NatalieM
PatrickR --> SarahW
PatrickR --> ScottK
@enduml
