# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
# package
# node
# folder
# frame
# cloud
# database
# interface
@startuml

package "Sipity" {
  component "File\nStorage" as SipityFS
  component "Descriptive\nMetadata\nStorage" as SipityDMS
  component "Batch Exporter" as SipityBE
  component "Business Logic" as SipityBL
  interface "API" as SipityAPI
  database "MySql"

}

package "Batch Ingest" as Batch {
  interface "API" as BatchAPI
}

package Noids {
  database MySQL as MySQLNoids
}

package OCLC
package Aleph

package OnBase

package Locabulary
SipityDMS ..> Locabulary : "for\ncontrolled\nvocabulary"

cloud "AWS" {
  component S3
}

SipityFS --> S3
SipityDMS --> MySql
SipityBE --> BatchAPI
SipityFS --> SipityBE
SipityDMS --> SipityBE
Batch ..( SipityAPI : "From Webhook\nprovided by\nSipity"
SipityBL --> MySql
SipityBL --> Noids
OnBase --> SipityAPI
SipityBL .(0).> Aleph
SipityBL .(0).> OCLC

@enduml
